[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra --reruns 1 --reruns-delay 1
markers =
    api: API regression tests
    ui: UI e2e tests powered by Selenium
